@url=http://localhost:3000/api
@verify_token={WHATSAPP_VERIFY_TOKEN}

### Verificación del webhook de WhatsApp
GET {{url}}/webhooks/whatsapp?hub.mode=subscribe&hub.verify_token={{verify_token}}&hub.challenge=12345

### Recibir mensaje de texto de WhatsApp
POST {{url}}/webhooks/whatsapp
Content-Type: application/json
X-Hub-Signature-256: sha256=e4435695954c5db6afafef2102c595182e5bdd5fe6fe13ae50552785b1ecbb3d

{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "123456789012345",
      "changes": [
        {
          "field": "messages",
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "5492641234567",
              "phone_number_id": "987654321098765"
            },
            "contacts": [
              {
                "profile": {
                  "name": "Fabian Lucena"
                },
                "wa_id": "5492641234567"
              }
            ],
            "messages": [
              {
                "from": "5492641234567",
                "id": "wamid.TEST_MESSAGE_ID_001",
                "timestamp": "1753390000",
                "text": {
                  "body": "Hola, este es un mensaje de prueba"
                },
                "type": "text"
              }
            ]
          }
        }
      ]
    }
  ]
}

### Mensaje enviado / entregado / leído
POST {{url}}/webhooks/whatsapp
Content-Type: application/json
X-Hub-Signature-256: sha256=1768d9b7a853279ddc3d9d08b5c7b288f8cbafdbc9a539507aa9a0943021293d

{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "123456789012345",
      "changes": [
        {
          "field": "messages",
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "5492641234567",
              "phone_number_id": "987654321098765"
            },
            "statuses": [
              {
                "id": "wamid.TEST_MESSAGE_ID_001",
                "status": "delivered",
                "timestamp": "1753390100",
                "recipient_id": "5492647654321"
              }
            ]
          }
        }
      ]
    }
  ]
}